Ally Events
TownyAdvanced/Towny pull request #4356
Opened 2020-10-07 03:16 UTC by ceeedric

Added ally events

#### Description: 

Adds the following events:
 - NationAcceptAllyRequestEvent
 - NationDenyAllyRequestEvent
 - NationPreAcceptAllyRequestEvent (cancellable)
 - NationPreDenyAllyRequestEvent (cancellable)
 - NationRemoveAllyEvent
 - NationPreRemoveAllyEvent (cancellable)
____
#### New Nodes/Commands/ConfigOptions: 

____
#### Relevant Towny Issue ticket:

____
- [x] I have tested this pull request for defects on a server. 

By making this pull request, I represent that I have the right to waive copyright and related rights to my contribution, and agree that all copyright and related rights in my contributions are waived, and I acknowledge that the TownyAdvanced organization has the copyright to use and modify my contribution under the Towny [License](https://github.com/LlmDl/Towny/blob/master/LICENSE.md) for perpetuity.

2020-10-07 12:31 UTC, LlmDl requested changes
Aside from the minor requested changes I'd like to know if the cancel-able events are actually removing the invitations that are denied. If they are not being removed (I suspect they aren't) then the king would end up just trying accept it over and over. 

There also needs to be a cancelled message shown to the person who's had their accept/deny action denied. You only need to add the new language string to the english.yml and I will copy it to the others.

2020-10-07 12:31 UTC, LlmDl commented on src/com/palmergames/bukkit/towny/command/NationCommand.java
> +import com.palmergames.bukkit.towny.event.*;
We don't do the wildcard imports. Please return it to how it was before.

2020-10-07 12:31 UTC, LlmDl commented on src/com/palmergames/bukkit/towny/command/NationCommand.java
> +
Remove whitespacing changes.

2020-10-07 18:44 UTC, silverwolfg11 requested changes
I don't really see the need for dividing each of these events up into a `pre` event and the actual event. The reason being is that this division is usually made when there is a case where we do not want the event to be cancelled and do not want to present an option of the event being cancelled.

In the cases of the events here, all of them are fine if they are cancelled and there is no case where we want to prevent cancellation of them.

Thus, I think it's best just to remove all the `pre` events and make the actual events cancellable. Developers who want to listen to the final state of these events can just listen to the event on `MONITOR` priority.

2020-10-12 15:36 UTC, LlmDl approved these changes

2020-10-12 15:36 UTC, merged