Create instances out of event war. War Revamp 2020.
TownyAdvanced/Towny pull request #4406
Opened 2020-10-31 18:59 UTC by LlmDl

#### Description: 

Details to follow...

____
#### New Nodes/Commands/ConfigOptions: 

____
#### Relevant Towny Issue ticket:

See linked project.

____
- [ ] I have tested this pull request for defects on a server. 

By making this pull request, I represent that I have the right to waive copyright and related rights to my contribution, and agree that all copyright and related rights in my contributions are waived, and I acknowledge that the TownyAdvanced organization has the copyright to use and modify my contribution under the Towny [License](https://github.com/LlmDl/Towny/blob/master/LICENSE.md) for perpetuity.

2020-11-17 18:06 UTC, LlmDl commented on src/com/palmergames/bukkit/towny/tasks/OnPlayerLogin.java
> +			universe.getWarEvent(player).getScoreManager().sendScores(player, 3);
Potentially list all active wars.

2020-12-03 21:08 UTC, TheFlagCourier requested changes
Rebased off my local master and ran `mvn javadoc:javadoc`.
Here's the pain points I see.

2020-12-03 21:08 UTC, TheFlagCourier commented on src/com/palmergames/bukkit/towny/object/TownyUniverse.java
>  	 */
`{@link TownyWorld#addWarZone(Coord)}` is unresolvable.

2020-12-03 21:08 UTC, TheFlagCourier commented on src/com/palmergames/bukkit/towny/object/TownyUniverse.java
>  	 */
`{@link TownyWorld#removeWarZone(Coord)}` is unresolvable.

2020-12-03 21:08 UTC, TheFlagCourier commented on src/com/palmergames/bukkit/towny/war/eventwar/WarBooks.java
> +	 */
Needs `@param war /description/`

2021-11-06 18:03 UTC, closed without merging