Improve message formatting in NationCommand and TownCommand
TownyAdvanced/Towny pull request #4494
Opened 2020-11-28 03:51 UTC by GNosii

#### Description: 

This PR is meant to improve message formatting in [NationCommand.java](https://github.com/TownyAdvanced/Towny/blob/master/src/com/palmergames/bukkit/towny/command/NationCommand.java) and [TownCommand.java](https://github.com/TownyAdvanced/Towny/blob/master/src/com/palmergames/bukkit/towny/command/NationCommand.java) by changing how some strings are formatted, making them more user-friendly and nice looking.
____

#### Changes made:
- Use `TownyMessaging.sendMsg` instead of `TownyMessaging.sendMessage`.
- Make nation and town messages use `TownyMessaging.sendPrefixedNationMessage` and `TownyMessaging.sendPrefixedTownMessage` whenever it might be useful.
- Make invite/ally request messages be nation/town messages instead of them being only shown to the user that revoked them.
- Make money-related messages use `TownyEconomyHandler.getFormattedBalance` to make them more user-friendly. (Example: "Player deposited 50000 into the town bank." is now displayed as "Player deposited $50,000 into the town bank.")
____
#### New Nodes/Commands/ConfigOptions: 

____
#### Relevant Towny Issue ticket:

____
- [x] I have tested this pull request for defects on a server. 

By making this pull request, I represent that I have the right to waive copyright and related rights to my contribution, and agree that all copyright and related rights in my contributions are waived, and I acknowledge that the TownyAdvanced organization has the copyright to use and modify my contribution under the Towny [License](https://github.com/LlmDl/Towny/blob/master/LICENSE.md) for perpetuity.

2020-11-28 06:16 UTC, docwhomc commented
Your commit messages could use some work. "Si" and "added a new line" are neither informative nor accurate.

2020-11-28 20:21 UTC, GNosii commented
> 
> 
> Your commit messages could use some work. "Si" and "added a new line" are neither informative nor accurate.

I do know, I had an small issue with git commiting so yeah, I'll try to improve commit messages

2020-11-29 14:06 UTC, LlmDl requested changes
Some things which need to be changed, overall I think it will improve the look of the feedback messages where your changes are good.

2020-11-29 14:06 UTC, LlmDl commented on src/com/palmergames/bukkit/towny/command/TownyAdminCommand.java
> +				TownyMessaging.sendMsg(getSender().getServer().getPlayer(getSender().getName()), TownyFormatter.getStatus(resident, player));
This is a spot that sendMessage should be used. Return to how it was.

2020-11-29 14:06 UTC, LlmDl commented on src/com/palmergames/bukkit/towny/command/TownyAdminCommand.java
> +				TownyMessaging.sendMsg(getSender().getServer().getPlayer(getSender().getName()), TownyFormatter.getStatus(town));
This is a spot that sendMessage should be used. Return to how it was.

2020-11-29 14:06 UTC, LlmDl commented on src/com/palmergames/bukkit/towny/command/TownyAdminCommand.java
> +				TownyMessaging.sendMsg(getSender().getServer().getPlayer(getSender().getName()), TownyFormatter.getStatus(nation));
This is a spot that sendMessage should be used. Return to how it was.

2020-11-29 20:01 UTC, LlmDl requested changes
There's still some major whitespacing issues. Some of the stuff needed to be changed in TownyAdminCommand were not completely done.

You definitely ought to rebase your branch off of master, so your changes are based off of the latest master.

2020-11-29 20:01 UTC, LlmDl commented on src/com/palmergames/bukkit/towny/command/TownyAdminCommand.java
> +				TownyMessaging.sendMessage(getSender().getServer().getPlayer(getSender().getName()), TownyFormatter.getStatus(nation));
Return the full line to how it was before.

2020-11-29 21:45 UTC, GNosii commented on src/com/palmergames/bukkit/towny/command/TownyAdminCommand.java
> +
rebased

2020-11-30 00:16 UTC, closed without merging