Fix trident lightning strike on pvp disabled plots
TownyAdvanced/Towny pull request #4631
Opened 2020-12-27 18:03 UTC by Kovalskki

#### Description: 
Fix trident lightning strike on pvp disabled plots
Known bug: Lightning Strike is disabled but sound of Channeling enchantment isnt cancelled

____
#### New Nodes/Commands/ConfigOptions: 

____
#### Relevant Towny Issue ticket:

____
- [x] I have tested this pull request for defects on a server. 

By making this pull request, I represent that I have the right to waive copyright and related rights to my contribution, and agree that all copyright and related rights in my contributions are waived, and I acknowledge that the TownyAdvanced organization has the copyright to use and modify my contribution under the Towny [License](https://github.com/LlmDl/Towny/blob/master/LICENSE.md) for perpetuity.

2020-12-27 22:26 UTC, Kovalskki commented
I tried canceling the channeling voice with EntityDamagedByEntityEvent but Trident is a entity. I cant access enchantments without nbt.

2020-12-27 22:28 UTC, Kovalskki commented
If you want, I can create a special class for this and keep the thrown spears in memory for fix the issue.

2020-12-27 23:16 UTC, LlmDl commented
This might be something that the API/damage_events branch could fix? I haven't had a chance to look over the changes in this PR yet.

2020-12-27 23:17 UTC, LlmDl commented
Also, I thought there was a lightning strike cause which could be useful.

2020-12-28 00:54 UTC, LlmDl requested changes

2020-12-28 00:54 UTC, LlmDl commented on src/com/palmergames/bukkit/towny/listeners/TownyWorldListener.java
> +	@EventHandler(priority = EventPriority.NORMAL)
I haven't yet seen if this PR is necessary after the api/damage_events branch is merged but here's a replacement block for the code below, which will cover both the wilderness and non-wilderness, as well as handle worlds where Towny isn't active or when Towny doesn't load properly:

```java
	@EventHandler(priority = EventPriority.NORMAL)
	public void onLightningStrike(LightningStrikeEvent event) {
		
		if (plugin.isError()) {
			event.setCancelled(true);
			return;
		}

		if (!TownyAPI.getInstance().isTownyWorld(event.getWorld()))
			return;
		
		TownyWorld townyWorld = null;
		try {
			townyWorld = TownyUniverse.getInstance().getDataSource().getWorld(event.getLightning().getWorld().getName());
		} catch (NotRegisteredException ignored) {}
		
		if (townyWorld != null && event.getCause().equals(LightningStrikeEvent.Cause.TRIDENT)) {
			event.setCancelled(CombatUtil.preventPvP(townyWorld, TownyAPI.getInstance().getTownBlock(event.getLightning().getLocation())));
		}
	}
```

2020-12-30 04:08 UTC, Kovalskki commented
I opened issue for this https://github.com/TownyAdvanced/Towny/issues/4647#issue-776200188

2020-12-30 04:08 UTC, closed without merging

2020-12-30 13:18 UTC, LlmDl commented
Ok, will you be applying the code I gave above and re-opening this PR?