Make applicable placeholders available when a player is offline (all …
TownyAdvanced/Towny pull request #4962
Opened 2021-05-27 19:07 UTC by BlakeStevenson

Make applicable placeholders available when a player is offline (all except for player_plot_* and player_location_*)

#### Description: 

Make certain placeholders useable when a player is offline. This is all except for plot and location placeholders.
____
#### New Nodes/Commands/ConfigOptions: 

____
#### Relevant Towny Issue ticket:

____
- [x] I have tested this pull request for defects on a server. 

By making this pull request, I represent that I have the right to waive copyright and related rights to my contribution, and agree that all copyright and related rights in my contributions are waived, and I acknowledge that the TownyAdvanced organization has the copyright to use and modify my contribution under the Towny [License](https://github.com/LlmDl/Towny/blob/master/LICENSE.md) for perpetuity.

2021-05-29 17:42 UTC, LlmDl requested changes
There's been some un-needed whitespace changes that have made the diff for this PR larger than it has to be. See if you can correct it please.

2021-05-31 23:06 UTC, AL1L commented
@LlmDl the diff actually has less whitespace in the new version...

2021-05-31 23:17 UTC, LlmDl commented
@AL1L I don't see any new version just the one commit which does this:  
![Capture](https://user-images.githubusercontent.com/879756/120248345-5f710200-c23c-11eb-934d-3cfb106dc35b.PNG)

2021-05-31 23:23 UTC, AL1L commented
weird

2021-06-27 19:45 UTC, LlmDl approved these changes

2021-07-12 11:08 UTC, merged