Feature/min deposit amount
TownyAdvanced/Towny pull request #5112
Opened 2021-07-24 21:03 UTC by illumeleet

#### Description: 

Add ability to set minimum deposit amount to towns & nations, also fixes some lang files malformations.
_accidentally got these two first commits, don't beat me pls_
____
#### New Nodes/Commands/ConfigOptions: 

town_min_deposit: '0.0'
nation_min_deposit: '0.0'

____
#### Relevant Towny Issue ticket:

____
- [x] I have tested this pull request for defects on a server. 

By making this pull request, I represent that I have the right to waive copyright and related rights to my contribution, and agree that all copyright and related rights in my contributions are waived, and I acknowledge that the TownyAdvanced organization has the copyright to use and modify my contribution under the Towny [License](https://github.com/LlmDl/Towny/blob/master/LICENSE.md) for perpetuity.

2021-07-24 21:05 UTC, LlmDl commented
The lang file version doesn't have to be bumped to .116 yet. Its also not recommended to add to all the lang files, if I do an update it means you have to rebase your langfiles to resolve the conflicts. I don't mind adding all the lang files after a PR is accepted.

2021-07-24 21:07 UTC, illumeleet commented
well, sorry. how should i commit language file changes then? Also, do you approve changes made in TownCommand & NationCommand?

2021-07-24 21:52 UTC, Warriorrrr commented
You can add your new lang strings just to the english.yml, makes rebasing less trivial. I'm pretty sure some economy plugins like TNE allow you to /pay directly into non-player accounts, which would bypass this setting.

2021-07-24 21:54 UTC, LlmDl requested changes
Very close to perfect, change the two lines I specified to use the formatter, and set the lang files back to 0.115 and lose the newline and #Added in 0.116.

2021-07-24 21:54 UTC, LlmDl commented on src/com/palmergames/bukkit/towny/command/NationCommand.java
> +					if (amount < nationMinDeposit) throw new TownyException(Translation.of("msg_err_deposit_must_be_higher_than", nationMinDeposit));
replace nationMinDeposit with `TownyEconomyHandler.getFormattedBalance(nationMinDeposit)`

2021-07-24 21:54 UTC, LlmDl commented on src/com/palmergames/bukkit/towny/command/TownCommand.java
> +					if (amount < townMinDeposit) throw new TownyException(Translation.of("msg_err_deposit_must_be_higher_than", townMinDeposit));
replace townMinDeposit with `TownyEconomyHandler.getFormattedBalance(townMinDeposit)`

2021-07-24 22:01 UTC, illumeleet commented
Done

2021-07-24 22:03 UTC, LlmDl approved these changes

2021-07-24 22:06 UTC, illumeleet commented
> You can add your new lang strings just to the english.yml
Thank you, will do next time

> I'm pretty sure some economy plugins like TNE allow you to /pay directly into non-player accounts, which would bypass this setting.
Not sure about that, but PR references default Towny town&nation deposit commands. If there will be any errors in future, i am ready to contribute.

2021-07-25 13:52 UTC, LlmDl requested changes
It has dawned on me that the tests you added which run in TownCommand and NationCommand should actually be ran in the MoneyUtil's commonTests() method.

```java 
		if (!withdraw) {
			double minAmount = nation ? TownySettings.getNationMinDeposit() : TownySettings.getTownMinDeposit();
			if (amount < minAmount)
				throw new TownyException(Translation.of("msg_err_deposit_must_be_higher_than", TownyEconomyHandler.getFormattedBalance(minAmount)));
		}
```

2021-07-25 20:24 UTC, illumeleet commented
Done

2021-07-25 20:29 UTC, illumeleet commented
> commonTests()

Totally missed this one, if this implementation won't get approved, i'll move tests to commonTests.

2021-07-25 21:16 UTC, LlmDl approved these changes

2021-07-25 21:18 UTC, merged