Translate Console givebonus warning
TownyAdvanced/Towny pull request #5514
Opened 2021-12-08 16:05 UTC by GNosii

#### Description: 

Allow translation of the "real-life money" warning that is shown when the console gives bonus townblocks to an player. To prevent server admins from removing this message, I added checks to the `Translation` class, which skips overrides for these strings.
____
#### New Nodes/Commands/ConfigOptions: 

____
#### Relevant Towny Issue ticket:

____
- [x] I have tested this pull request for defects on a server. 

By making this pull request, I represent that I have the right to waive copyright and related rights to my contribution, and agree that all copyright and related rights in my contributions are waived, and I acknowledge that the TownyAdvanced organization has the copyright to use and modify my contribution under the Towny [License](https://github.com/LlmDl/Towny/blob/master/LICENSE.md) for perpetuity.

2021-12-08 18:26 UTC, LlmDl commented
Something like this should be done in the Translation.java:

Extracting the translation value to its own method:

Starting from line 128:
```java
						if (values != null) {
							translations.computeIfAbsent(lang, k -> new HashMap<>());
							for (Map.Entry<String, Object> entry : values.entrySet())
								translations.get(lang).put(entry.getKey().toLowerCase(Locale.ROOT), getTranslationValue(entry));
						}
					} catch (Exception e) {
						e.printStackTrace();
					}
				}
			}
		}

		//Can be null if no overrides have been added
		if (globalOverrides != null)
			for (Map.Entry<String, Object> entry : globalOverrides.entrySet())
				for (String lang : translations.keySet())
					translations.get(lang).put(entry.getKey().toLowerCase(Locale.ROOT), getTranslationValue(entry));
		
		defaultLocale = loadDefaultLocale();		
		Towny.getPlugin().getLogger().info(String.format("Successfully loaded translations for %d languages.", translations.keySet().size()));
		HelpMenu.loadMenus();
	}
	
	private static String getTranslationValue(Entry<String, Object> entry) {
		// Messages blocked from being overriden.
		if (entry.getKey().toLowerCase().startsWith("msg_ptw_warning")) {
			String msg = translations.get(defaultLocale.toString()).get(entry.getKey());

			// It's extremely possible the jar was edited and the string is missing/was modified.
			if (!msg.contains("EULA") && !msg.contains("Towny")) {
				switch (entry.getKey()) {
					case "msg_ptw_warning_1": {
						msg = "If you have paid any real-life money for these townblocks please understand: the server you play on is in violation of the Minecraft EULA and the Towny license.";
						break;
					}
					case "msg_ptw_warning_2": {
						msg = "The Towny team never intended for townblocks to be purchaseable with real money.";
						break;
					}
					case "msg_ptw_warning_3": {
						msg = "If you did pay real money you should consider playing on a Towny server that respects the wishes of the Towny Team.";
						break;
					}
				default:
					break;
				}
			}
			hasBlockedOverrides = true;
			return msg;
		}
		return String.valueOf(entry.getValue());
	}

```

Note that `if (!msg.contains("EULA") && !msg.contains("Towny")) {` will fail on 2 of the 3 messages.

2021-12-09 00:42 UTC, LlmDl requested changes
I've added a suggestion to use for the getTranslationValue() method.

My only issue with this right now is it ends up not using any Translation's PTW messages. It is always using the defaultLocale's lang file, ignoring the ptw entries in all the other lang files. In order to make it actually deliver the message to the player in their own locale the lang value would have to be passed along: `getTranslationValue(lang, entry)`.

2021-12-09 00:42 UTC, LlmDl commented on src/com/palmergames/bukkit/towny/object/Translation.java
> +		return String.valueOf(entry.getValue());
```suggestion
		// Messages blocked from being overriden.
		if (entry.getKey().toLowerCase().startsWith("msg_ptw_warning")) {
			// Get the defaultLocale's translation of the PTW warnings.
			String msg = translations.get(defaultLocale.toString()).get(entry.getKey());
			hasBlockedOverrides = true;
			// It's extremely possible the jar was edited and the string is missing/was modified.
			if (!msg.contains("Towny"))
				// Return a hard-coded message, the translation in the jar was likely tampered with.
				return switch (entry.getKey()) {
					case "msg_ptw_warning_1" -> "If you have paid any real-life money for these townblocks please understand: the server you play on is in violation of the Minecraft EULA and the Towny license.";
					case "msg_ptw_warning_2" -> "The Towny team never intended for townblocks to be purchaseable with real money.";
					case "msg_ptw_warning_3" -> "If you did pay real money you should consider playing on a Towny server that respects the wishes of the Towny Team.";
					default -> throw new IllegalArgumentException("Unexpected value: " + entry.getKey());
				};
			// Return the defaultLocale's message, it appears to have been left alone.
			return msg;
		}
		// Return the normal translation of the entry.
		return String.valueOf(entry.getValue());
```

2021-12-11 20:27 UTC, LlmDl requested changes

2021-12-11 20:27 UTC, LlmDl commented on src/com/palmergames/bukkit/towny/object/Translation.java
> +			String msg = String.valueOf(translations.get(defaultLocale).get(entry.getKey()));
```suggestion
			String msg = String.valueOf(entry.getValue());
```

2021-12-11 20:27 UTC, LlmDl commented on src/com/palmergames/bukkit/towny/object/Translation.java
> +			String msg = String.valueOf(translations.get(defaultLocale).get(entry.getKey()));
I think this is required in order for any of the translated messages to be used instead of the default locale only.

2021-12-11 22:00 UTC, LlmDl commented
Can you re-test that this works, and also works with various translations?

2021-12-15 16:40 UTC, GNosii commented
![image](https://user-images.githubusercontent.com/65878291/146227242-cebcba7d-3eee-4c04-b433-794aa1607fc1.png)
Confirmed this works by changing JAR's `es-ES.yml` strings and switching between `English (United States)` and `Español (España)`

2021-12-15 21:01 UTC, merged