Nation tax percent
TownyAdvanced/Towny pull request #6262
Opened 2022-10-24 18:15 UTC by PainOchoco

#### Description:

Adds Tax percentage for nations

____
#### New Nodes/Commands/ConfigOptions: 

##### Commands
- `/nation toggle taxpercent`
- `/nation set taxpercentcap`

##### Permissions
- towny.command.nation.toggle.taxpercent
- towny.command.nation.set.taxpercentcap
____
#### Relevant Towny Issue ticket:

#6106 

____
- [ ] I have tested this pull request for defects on a server. (Not everything yet)

By making this pull request, I represent that I have the right to waive copyright and related rights to my contribution, and agree that all copyright and related rights in my contributions are waived, and I acknowledge that the TownyAdvanced organization has the copyright to use and modify my contribution under the Towny [License](https://github.com/LlmDl/Towny/blob/master/LICENSE.md) for perpetuity.

2022-10-24 18:48 UTC, LlmDl requested changes
Spotted a couple of small things, lookin' good so far though.

2022-10-24 18:48 UTC, LlmDl commented on src/com/palmergames/bukkit/config/ConfigNodes.java
> +            "true",
Having this set to true would be a shift from the current default behaviour. This should be made false.

2022-10-24 18:48 UTC, LlmDl commented on src/com/palmergames/bukkit/towny/TownySettings.java
> +        return getDouble(ConfigNodes.ECO_DAILY_TAXES_MAX_TOWN_TAX_PERCENT_AMOUNT);
Remove diff

2022-10-24 18:48 UTC, LlmDl commented on src/com/palmergames/bukkit/towny/db/SQL_Schema.java
> +        columns.add("`taxpercent` bool NOT NULL DEFAULT '0'");
Also needs a maxPercentTaxAmount

2022-10-24 19:36 UTC, PainOchoco commented
I think I've tested everything, (except the save to sql because it's a bit complicated to setup but there should not be any problem as I followed the same methods as the town) but make sure to double check just in case I missed something.

(Also please add the hacktoberfest-accepted :P)

2022-10-26 21:51 UTC, LlmDl approved these changes

2022-10-26 21:51 UTC, LlmDl commented on src/com/palmergames/bukkit/towny/TownySettings.java
> +        return getDouble(ConfigNodes.ECO_DAILY_TAXES_MAX_TOWN_TAX_PERCENT_AMOUNT);
Unneeded changes on this line.

2022-10-28 14:25 UTC, merged