Make level related errors easier to debug
TownyAdvanced/Towny pull request #6524
Opened 2023-03-04 16:21 UTC by Warriorrrr

#### Description: 

____
#### New Nodes/Commands/ConfigOptions: 

____
#### Relevant Towny Issue ticket:

____
- [ ] I have tested this pull request for defects on a server. 

By making this pull request, I represent that I have the right to waive copyright and related rights to my contribution, and agree that all copyright and related rights in my contributions are waived, and I acknowledge that the TownyAdvanced organization has the copyright to use and modify my contribution under the Towny [License](https://github.com/LlmDl/Towny/blob/master/LICENSE.md) for perpetuity.

2023-03-05 13:36 UTC, LlmDl requested changes
I would also be nice to know that the loading of town/nation levels still works with the config migrator, now that it isn't all using strings.

2023-03-05 13:36 UTC, LlmDl commented on src/com/palmergames/bukkit/towny/TownySettings.java
> +					levelGet(level, "nation levels", numResidentsIndex, "mayorPostfix", ""),
these "nation levels" should be "town levels" for the correct error messaging.

2023-03-06 22:21 UTC, Warriorrrr commented
The loading is still essentially the same so I assume the config migrator will play nice, levelGet is equivalent to level.get("key").toString() but with some nice error messaging

2023-03-06 22:26 UTC, LlmDl commented
Looks good to me:
```
[16:25:28] [Server thread/INFO]: [Towny] Config: 0.98.6.3 applying 1 automatic update...
[16:25:28] [Server thread/INFO]: [Towny] Config: 0.98.6.5 applying 2 automatic updates...
[16:25:28] [Server thread/INFO]: [Towny] Config: 0.98.6.7 applying 3 automatic updates...
```

2023-03-06 22:27 UTC, merged