Add floodfill claim command
TownyAdvanced/Towny pull request #7012
Opened 2023-09-29 17:20 UTC by Warriorrrr

#### Description: 

Adds a new /t claim fill command that automatically selects all unclaimed plots in whatever outline the player is standing in

todo:
optimizations
actual feedback messages
____
#### Relevant Towny Issue ticket:

Closes #6624

____
- [ ] I have tested this pull request for defects on a server. 

By making this pull request, I represent that I have the right to waive copyright and related rights to my contribution, and agree that all copyright and related rights in my contributions are waived, and I acknowledge that the TownyAdvanced organization has the copyright to use and modify my contribution under the Towny [License](https://github.com/LlmDl/Towny/blob/master/LICENSE.md) for perpetuity.

2023-09-29 17:23 UTC, Warriorrrr commented on Towny/src/main/java/com/palmergames/bukkit/towny/utils/BorderUtil.java
> +				if (!candidate.hasTownBlock() && !visited.contains(candidate) && !coords.contains(candidate)) {
need to check whether we're hitting a town that isn't our own here and also fail if so

2023-10-16 20:46 UTC, LlmDl requested changes

2023-10-16 20:46 UTC, LlmDl commented on Towny/src/main/java/com/palmergames/bukkit/towny/command/TownCommand.java
> +				TownyMessaging.sendErrorMsg(player, result.feedback());
Should this be a `throw new TownyException()` situation? It looks like we'll still be passing on a selection from the results.coords().

2023-10-16 20:46 UTC, LlmDl commented on Towny/src/main/java/com/palmergames/bukkit/towny/permissions/PermissionNodes.java
> +			TOWNY_COMMAND_TOWN_CLAIM_FILL("towny.command.town.claim.fill"),
This should get added to the plugin.yml as a child node of towny.command.town.claim.*

2023-10-16 20:46 UTC, LlmDl commented on Towny/src/main/java/com/palmergames/bukkit/towny/utils/BorderUtil.java
> +				if (townBlock != null && townBlock.hasTown() && !town.equals(townBlock.getTownOrNull())) {
This could use `candidate.hasTown(town)` instead of the three tests.

2023-10-16 20:46 UTC, LlmDl commented on Towny/src/main/java/com/palmergames/bukkit/towny/utils/BorderUtil.java
> +				if (townBlock == null && !visited.contains(candidate) && !coords.contains(candidate)) {
This could use candidate.isWilderness() instead of townBlock == null, then we can do away with the whole townBlock variable.

2023-10-16 20:46 UTC, LlmDl commented on Towny/src/main/java/com/palmergames/bukkit/towny/utils/BorderUtil.java
> +	public static @NotNull FloodfillResult getFloodFillableCoords(final @NotNull Town town, final @NotNull WorldCoord origin) {
The only other thing I can see being useful here is being able to test if the town has enough claims to even claim the filled area. We would have to take into account towns with unlimited claims as well.

2023-10-16 20:49 UTC, LlmDl commented on Towny/src/main/java/com/palmergames/bukkit/towny/utils/BorderUtil.java
> +
```
if (!town.hasUnlimitedClaims() && valid.size() > town.getAvailableTownBlocks())
   return FloodfillResult.notEnoughClaims();
```

2023-10-16 20:49 UTC, LlmDl commented on Towny/src/main/java/com/palmergames/bukkit/towny/utils/BorderUtil.java
> +
Something like the above would stop a town with one or no claims available from flood filling.

2023-10-23 21:32 UTC, LlmDl approved these changes

2023-10-23 21:34 UTC, merged