Allow setting a default plot price of -1
TownyAdvanced/Towny pull request #7313
Opened 2024-03-16 10:18 UTC by Warriorrrr

#### Description: 

____
#### Relevant Towny Issue ticket:

Closes #7295

____
- [ ] I have tested this pull request for defects on a server. 

By making this pull request, I represent that I have the right to waive copyright and related rights to my contribution, and agree that all copyright and related rights in my contributions are waived, and I acknowledge that the TownyAdvanced organization has the copyright to use and modify my contribution under the Towny [License](https://github.com/LlmDl/Towny/blob/master/LICENSE.md) for perpetuity.

2024-03-16 13:23 UTC, LlmDl requested changes

2024-03-16 13:23 UTC, LlmDl commented on Towny/src/main/java/com/palmergames/bukkit/towny/command/TownCommand.java
These changes could get replaced by a new method in MathUtil:
```java
	
	public static double getPositiveDoubleOrThrow(String input) throws TownyException {
		double d = getDoubleOrThrow(input);
		if (d < 0)
			throw new TownyException(Translatable.of("msg_err_negative"));
		return d;
	}
```

This would match up with the one we already have for ints.

2024-05-05 08:31 UTC, Warriorrrr commented on Towny/src/main/java/com/palmergames/bukkit/towny/command/TownCommand.java
I wouldn't be able to differentiate between the exception from the input not being a double and the input being negative, I want to allow the amount to be set to a negative number here

2024-05-06 14:45 UTC, LlmDl approved these changes

2024-05-06 14:45 UTC, merged