Add option to use world key instead of world name
TownyAdvanced/Towny pull request #7388
Opened 2024-04-28 00:44 UTC by gecko10000

#### Description: 
This adds the option to use a world's key for the webmap link instead of the world name. For example, [squaremap](https://github.com/jpenilla/squaremap/issues/202) uses the world's namespaced key and doesn't integrate with Towny's approach to this.

____
#### New Nodes/Commands/ConfigOptions: 
```
  - New Config Option: plugin.interfacing.web_map.world_name_uses_world_key
    - Default: false
    - If enabled, the world name placeholder will be replaced with the world key instead of the Bukkit name.
    - This should be enabled if you use SquareMap.
```

____
#### Relevant Towny Issue ticket:
N/A

____
- [x] I have tested this pull request for defects on a server.

By making this pull request, I represent that I have the right to waive copyright and related rights to my contribution, and agree that all copyright and related rights in my contributions are waived, and I acknowledge that the TownyAdvanced organization has the copyright to use and modify my contribution under the Towny [License](https://github.com/LlmDl/Towny/blob/master/LICENSE.md) for perpetuity.

2024-04-28 00:46 UTC, gecko10000 commented
Not sure what happened with the newlines, but I re-added them.

2024-04-28 13:48 UTC, Warriorrrr requested changes

2024-04-28 13:48 UTC, Warriorrrr commented on Towny/src/main/java/com/palmergames/bukkit/towny/TownyFormatter.java
> +			String worldName = TownySettings.isUsingWorldKeyForWorldName() ? world.getKey().toString() : world.getName();
We still support 1.16 (for now) and spigot's World class didn't implement Keyed yet back then, it was only added in 1.18.2 while paper already had it

```suggestion
			String worldName = TownySettings.isUsingWorldKeyForWorldName() && ( PaperLib.isPaper() || MinecraftVersion.isNewerThanOrEquals(MinecraftVersion.1_18_2)) ? world.getKey().toString() : world.getName();

```

2024-04-30 15:06 UTC, LlmDl approved these changes

2024-05-02 16:28 UTC, Warriorrrr approved these changes

2024-05-06 14:51 UTC, merged