Add a new permission flag to toggle snowfall, like you would for firespread
TownyAdvanced/Towny pull request #7690
Opened 2024-12-02 10:24 UTC by jwkerr

#### Description: 

I made this pull request as in my experience many people dread making towns in snow due to the constant covering of your builds in snow. It takes a lot of time and maintenance to keep your town clean, I've seen some go to the extreme of placing thousands of iron bars at the highest Y level to prevent snowfall. I think it is fair to add the ability to toggle this for players, if lag is a concern server admins can force snowfall on or otherwise remove access to turning it off.
____
#### New Nodes/Commands/ConfigOptions: 

New config nodes:
- `new_world_settings.snow.world_snowfall_enabled`
- `new_world_settings.snow.force_snow_on`

New commands and their permissions:
- `/town toggle snow`
  - `towny.command.town.toggle.snow`
- `/plot toggle snow`
  - `towny.command.plot.toggle.snow`
- `/res toggle snow`
  - `towny.command.resident.toggle.snow`
- `/tw toggle snow`
  - `towny.command.townyworld.toggle.snow`
- `/tw toggle forcesnow`
  - `towny.command.townyworld.toggle.forcesnow`
____
#### Relevant Towny Issue ticket:

N/A

____
- [x] I have tested this pull request for defects on a server. 

By making this pull request, I represent that I have the right to waive copyright and related rights to my contribution, and agree that all copyright and related rights in my contributions are waived, and I acknowledge that the TownyAdvanced organization has the copyright to use and modify my contribution under the Towny [License](https://github.com/LlmDl/Towny/blob/master/LICENSE.md) for perpetuity.

2024-12-02 10:26 UTC, jwkerr commented
some things i know need to be looked at:
- i think plot perm hud might break, couldn't test it as my test server is folia but it might make it too big
- not sure if i'm misunderstanding something but afaik i made the default behaviour for towns that snowfall is on, however in my test server it was off, the config's default value is true though and the value displayed was how it functioned in game

2024-12-02 12:25 UTC, LlmDl requested changes

2024-12-02 12:25 UTC, LlmDl commented on Towny/src/main/java/com/palmergames/bukkit/towny/huds/PermHUD.java
You can undo the changes to this class, there's no more room available in the perm hud scoreboard, its already at 15 lines.

2024-12-02 12:25 UTC, LlmDl commented on Towny/src/main/java/com/palmergames/bukkit/config/ConfigNodes.java
> +	FLAGS_TOWN_DEF_SNOW("default_perm_flags.town.default.snow", "true"), // TODO: fruit add node to config
Is this TODO ready to go?

2024-12-02 12:25 UTC, LlmDl commented on Towny/src/main/java/com/palmergames/bukkit/towny/command/HelpMenu.java
This class needs more help lines, the ones I've spotted are

TA_TOWN_TOGGLE,
TOWN_TOGGLE_HELP,
PLOT_GROUP_TOGGLE,
PLOT_TOGGLE

2024-12-02 12:25 UTC, LlmDl commented on Towny/src/main/java/com/palmergames/bukkit/towny/command/PlotCommand.java
> +			TownyMessaging.sendMsg(player, Translatable.of("msg_changed_snow", "the Plot", townBlock.getPermissions().snow ? Translatable.of("enabled") : Translatable.of("disabled")));
This does need a `break;` added to the end of it, I think you'd mentioned this.

2024-12-02 12:25 UTC, LlmDl commented on Towny/src/main/java/com/palmergames/bukkit/towny/command/PlotCommand.java
> +					endingMessage = Translatable.of("msg_changed_snow", Translatable.of("msg_the_plot_group"), groupBlock.getPermissions().snow ? Translatable.of("enabled") : Translatable.of("disabled"));
Another missed `break;`

2024-12-02 12:25 UTC, LlmDl commented on Towny/src/main/java/com/palmergames/bukkit/towny/command/TownCommand.java
> +		// TODO: add these messages
Is this TODO complete?

2024-12-02 12:25 UTC, LlmDl commented on Towny/src/main/java/com/palmergames/bukkit/towny/db/TownySQLSource.java
Adding anything to the SQLSource also requires an addition to the SQLSchema class, so the columns will be created.

2024-12-02 12:25 UTC, LlmDl commented on Towny/src/main/resources/lang/en-US.yml
> +msg_changed_snow: '&cSnowfall in %s is now %s'
Missing a period on the end of this string.

2024-12-02 12:25 UTC, LlmDl commented on Towny/src/main/resources/lang/en-US.yml
> +#Seen in /plot perm hud:
This can be removed.

2024-12-27 13:45 UTC, LlmDl approved these changes

2024-12-27 13:48 UTC, LlmDl reviewed
Before I merge this I would like you to tell me what happens to all of the plots before this feature is added.

Does the town/resident/plot require their TownyPermission to include Snow in order to have snow fall?

Will this update mean that all of a sudden snow accumulates nowhere on the server until those towns, residents, plots have their snow enabled?

2024-12-27 18:25 UTC, jwkerr commented
as I wrote in a previous comment, I noticed that it defaulted to false and I don't know how to change that

2024-12-27 18:25 UTC, jwkerr commented
https://github.com/TownyAdvanced/Towny/pull/7690#issuecomment-2511141573

2024-12-27 19:37 UTC, LlmDl commented
the property in the townypermission should probably get renamed to `nosnow`, and have the logic flipped. If this PR were to cause all of the snow to not function anywhere it would be disruptive.

2025-01-06 18:45 UTC, LlmDl requested changes
As commented earlier this will have to get overhauled to work in the opposite manner, or we'll end up breaking snow everywhere on already-existing servers.

Also moved this off of the 0.101.1.0 milestone.

2025-01-08 01:00 UTC, jwkerr commented
@LlmDl i don't think it needs to be flipped, i just don't understand why this code:

https://github.com/TownyAdvanced/Towny/blob/ca361e42c53e7637064d1da3ee624ef636baa485/Towny/src/main/java/com/palmergames/bukkit/towny/object/Town.java#L126
https://github.com/TownyAdvanced/Towny/blob/83c9035d5e77b6930f902ed9f55bb808a0645e11/Towny/src/main/java/com/palmergames/bukkit/towny/object/TownyPermission.java#L306

doesn't load towns existing before this change as having snowfall enabled as that is the default, towns created afterwards have it enabled so why wouldn't old ones? if we can just fix that behaviour it should be ready to merge

2025-01-08 01:06 UTC, LlmDl commented
https://github.com/TownyAdvanced/Towny/blob/ca361e42c53e7637064d1da3ee624ef636baa485/Towny/src/main/java/com/palmergames/bukkit/towny/object/Town.java#L126

This is only kept when a town is newly created; when a town is loaded on startup it will use this constructor, then the permission line is changed when the town's permission line is read from the db.

2025-01-08 01:08 UTC, LlmDl commented
> doesn't load towns existing before this change as having snowfall enabled as that is the default, towns created afterwards have it enabled so why wouldn't old ones? if we can just fix that behaviour it should be ready to merge

That's why it would make more sense for the db-aspect of it to assume that snow is wanted, and only get put on the perm line when snow is not wanted.

2025-01-08 07:01 UTC, jwkerr commented
by db side, do you mean for example changing this sql default from a 0 to a 1?

https://github.com/TownyAdvanced/Towny/blob/83c9035d5e77b6930f902ed9f55bb808a0645e11/Towny/src/main/java/com/palmergames/bukkit/towny/db/SQLSchema.java#L300

and if that is correct, i'm unsure what i would need to change to alter the default if flatfile is used, i've been digging around the code but its a bit hard for me to follow what exactly is used in which loading circumstances

and as for not showing it on the perm line, i can do that, and if you would like i can also or alternatively have it show in red if it is off unlike the other perm line settings that show as green if off since it might make more sense

2025-01-08 07:04 UTC, jwkerr commented
i suppose an else statement here setting it to true if the key is null would work?

https://github.com/TownyAdvanced/Towny/blob/83c9035d5e77b6930f902ed9f55bb808a0645e11/Towny/src/main/java/com/palmergames/bukkit/towny/db/TownyFlatFileSource.java#L1358

2025-01-08 07:16 UTC, jwkerr commented
nvm it should be a change under loadTown right

2025-01-08 07:40 UTC, jwkerr commented
okay after https://github.com/TownyAdvanced/Towny/pull/7690/commits/0729040a0cb1e326b9294eab5e1293583ba649ce i deleted all my data, reloaded on a non-snowfall version, made a town, loaded a snowfall version and it was defaulted to on, so towns should no longer unexpectedly stop snowing

2025-01-11 12:54 UTC, LlmDl requested changes
I like the hiding of the snow flag when it isn't blocking snow, that should make things a bit cleaner. 

I'm not so sure I like this part of the loading though:
```java
		// To update perm lines from before the snowfall toggle was added to make sure snow doesn't unexpectedly stop falling
		snow = true; 
```
It feels like a band-aid or one-off fix to something that should be approached from a different direction.

I would rather the snow property that gets saved be a `nosnow`, which is only saved into residents/plots/towns' permission lines in the DB when a player doesn't want snow. Rather than saving `snow` into every resident/plot/town permission line. My thinking is that fire is fairly uncommon to want on in a plot, same with explosions. Only in the rare occurrence where a player wants fire, explosions, mobs on, does the DB get the property added to it. Not wanting snow is also the rarer state of this property and we should reflect that in how the property acts when it isn't present in the permission line.

2025-03-08 01:12 UTC, Nicky-Who commented
![2025-03-08_10-11](https://github.com/user-attachments/assets/08c11311-126d-429a-b14d-0f6a3e51ebde)

2025-03-08 01:13 UTC, Nicky-Who commented
So snow now falls at elevation and in warm biomes. My deck is in warm ocean 
I think this is new since the 1.21.4 update.

2025-03-08 13:50 UTC, LlmDl commented
Your deck doesn't look strong enough to support that sort of snow fall. You should shovel it. /s

@jwkerr are you still working on this?

2025-06-27 09:58 UTC, squeaky2137 commented
Willing to finish this if wanted and / or if he doesnt want to / doesnt respond

2025-06-27 13:04 UTC, jwkerr commented
that would be good because i don't have the motivation to do it

2025-09-27 16:36 UTC, closed without merging