Add config option for Closed Economy UUID
TownyAdvanced/Towny pull request #7704
Opened 2024-12-21 07:33 UTC by turtledude01

#### Description: 

Add config option for Closed Economy UUID to support modern Economy plugins
____
#### New Nodes/Commands/ConfigOptions: 

New Config Option: 
closed_economy: server_account_uuid

____
#### Relevant Towny Issue ticket:

____
- [x] I have tested this pull request for defects on a server. 

By making this pull request, I represent that I have the right to waive copyright and related rights to my contribution, and agree that all copyright and related rights in my contributions are waived, and I acknowledge that the TownyAdvanced organization has the copyright to use and modify my contribution under the Towny [License](https://github.com/LlmDl/Towny/blob/master/LICENSE.md) for perpetuity.

2024-12-21 12:24 UTC, LlmDl requested changes
Looks good aside from the unneeded diff. Thanks for the first-time contribution.

2024-12-21 12:24 UTC, LlmDl commented on Towny/src/main/java/com/palmergames/bukkit/towny/object/economy/TownyServerAccount.java
> +
Unneeded diff should be removed here.

2024-12-22 17:19 UTC, turtledude01 commented
Strange, Intellij was not telling me that was a change, and I never touched that.  Should be fixed now though

2024-12-23 11:42 UTC, LlmDl approved these changes

2024-12-27 13:28 UTC, merged